# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profiel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profiel_image',
            new_name='profile_image',
        ),
    ]
